---
.config/nvim/pack/plugins/opt/cmp-buffer:
  type: git-repo
  url: https://github.com/hrsh7th/cmp-buffer
.config/nvim/pack/plugins/opt/cmp-nvim-lsp:
  type: git-repo
  url: https://github.com/hrsh7th/cmp-nvim-lsp
.config/nvim/pack/plugins/opt/gitsigns.nvim:
  type: git-repo
  url: https://github.com/lewis6991/gitsigns.nvim
.config/nvim/pack/plugins/opt/hydra.nvim:
  type: git-repo
  url: https://github.com/anuvyklack/hydra.nvim
.config/nvim/pack/plugins/opt/kanagawa.nvim:
  type: git-repo
  url: https://github.com/rebelot/kanagawa.nvim
.config/nvim/pack/plugins/opt/leap.nvim:
  type: git-repo
  url: https://github.com/ggandor/leap.nvim
.config/nvim/pack/plugins/opt/lsp_lines.nvim:
  type: git-repo
  url: https://git.sr.ht/~whynothugo/lsp_lines.nvim
.config/nvim/pack/plugins/opt/lualine.nvim:
  type: git-repo
  url: https://github.com/nvim-lualine/lualine.nvim
.config/nvim/pack/plugins/opt/mini.ai:
  type: git-repo
  url: https://github.com/echasnovski/mini.ai
.config/nvim/pack/plugins/opt/mini.comment:
  type: git-repo
  url: https://github.com/echasnovski/mini.comment
.config/nvim/pack/plugins/opt/mini.indentscope:
  type: git-repo
  url: https://github.com/echasnovski/mini.indentscope
.config/nvim/pack/plugins/opt/mini.surround:
  type: git-repo
  url: https://github.com/echasnovski/mini.surround
.config/nvim/pack/plugins/opt/mini.trailspace:
  type: git-repo
  url: https://github.com/echasnovski/mini.trailspace
.config/nvim/pack/plugins/opt/neoscroll.nvim:
  type: git-repo
  url: https://github.com/karb94/neoscroll.nvim
.config/nvim/pack/plugins/opt/noice.nvim:
  type: git-repo
  url: https://github.com/folke/noice.nvim
.config/nvim/pack/plugins/opt/nui.nvim:
  type: git-repo
  url: https://github.com/MunifTanjim/nui.nvim
.config/nvim/pack/plugins/opt/null-ls.nvim:
  type: git-repo
  url: https://github.com/jose-elias-alvarez/null-ls.nvim
.config/nvim/pack/plugins/opt/nvim-autopairs:
  type: git-repo
  url: https://github.com/windwp/nvim-autopairs
.config/nvim/pack/plugins/opt/nvim-cmp:
  type: git-repo
  url: https://github.com/hrsh7th/nvim-cmp
.config/nvim/pack/plugins/opt/nvim-dap:
  type: git-repo
  url: https://github.com/mfussenegger/nvim-dap
.config/nvim/pack/plugins/opt/nvim-dap-go:
  type: git-repo
  url: https://github.com/leoluz/nvim-dap-go
.config/nvim/pack/plugins/opt/nvim-goc.lua:
  type: git-repo
  url: https://github.com/rafaelsq/nvim-goc.lua
.config/nvim/pack/plugins/opt/nvim-lspconfig:
  type: git-repo
  url: https://github.com/neovim/nvim-lspconfig
.config/nvim/pack/plugins/opt/nvim-notify:
  type: git-repo
  url: https://github.com/rcarriga/nvim-notify
.config/nvim/pack/plugins/opt/nvim-treehopper:
  type: git-repo
  url: https://github.com/mfussenegger/nvim-treehopper
.config/nvim/pack/plugins/opt/nvim-treesitter:
  type: git-repo
  url: https://github.com/nvim-treesitter/nvim-treesitter
.config/nvim/pack/plugins/opt/nvim-treesitter-textobjects:
  type: git-repo
  url: https://github.com/nvim-treesitter/nvim-treesitter-textobjects
.config/nvim/pack/plugins/opt/nvim-unception:
  type: git-repo
  url: https://github.com/samjwill/nvim-unception
.config/nvim/pack/plugins/opt/plenary.nvim:
  type: git-repo
  url: https://github.com/nvim-lua/plenary.nvim
.config/nvim/pack/plugins/opt/quick-scope:
  type: git-repo
  url: https://github.com/unblevable/quick-scope
.config/nvim/pack/plugins/opt/rnvimr:
  type: git-repo
  url: https://github.com/kevinhwang91/rnvimr
.config/nvim/pack/plugins/opt/telescope.nvim:
  type: git-repo
  url: https://github.com/nvim-telescope/telescope.nvim
.config/nvim/pack/plugins/opt/toggleterm.nvim:
  type: git-repo
  url: https://github.com/akinsho/toggleterm.nvim
.config/nvim/pack/plugins/opt/undotree:
  type: git-repo
  url: https://github.com/mbbill/undotree
.config/nvim/pack/plugins/opt/vim-illuminate:
  type: git-repo
  url: https://github.com/RRethy/vim-illuminate
.config/nvim/pack/plugins/opt/vim-sleuth:
  type: git-repo
  url: https://github.com/tpope/vim-sleuth
.config/nvim/pack/plugins/opt/which-key.nvim:
  type: git-repo
  url: https://github.com/folke/which-key.nvim
.config/nvim/pack/plugins/opt/yanky.nvim:
  type: git-repo
  url: https://github.com/gbprod/yanky.nvim
