when:
  - event: push
    branch: main
  - event: pull_request

steps:
  - name: build
    image: bash
    commands:
      - nix -vL --show-trace build .#nixosConfigurations.simmons.config.system.build.toplevel
      - nix -vL --show-trace build .#nixosConfigurations.hyperion.config.system.build.toplevel
