[theme]
name = "gruvbox-dark"

[icons]
name = "awesome5"

[[block]]
block = "net"
format = "{ssid} {signal_strength} {ip} {speed_up;K*b} {speed_down;K*b}"
interval = 5

[[block]]
block = "toggle"
text = "BelWü VPN UDP"
command_state = "systemctl is-active openvpn-client@via-udp | grep -v inactive"
command_on = "sudo systemctl start openvpn-client@via-udp"
command_off = "sudo systemctl stop openvpn-client@via-udp"
interval = 5

[[block]]
block = "toggle"
text = "BelWü VPN TCP"
command_state = "systemctl is-active openvpn-client@via-tcp | grep -v inactive"
command_on = "sudo systemctl start openvpn-client@via-tcp"
command_off = "sudo systemctl stop openvpn-client@via-tcp"
interval = 5
