[theme]
name = "gruvbox-dark"

[icons]
name = "awesome5"
[icons.overrides]
time = ""
music = ""

[[block]]
block = "sound"
on_click = "swaymsg -q -- exec pavucontrol"

[[block]]
block = "custom"
command = ''' /home/danieln/.config/sway/get_mic_status.sh '''
signal = 4
interval = "once"
on_click = "pactl set-source-mute @DEFAULT_SOURCE@ toggle && pkill -SIGRTMIN+4 i3status-rs"
json = true

[[block]]
block = "time"
interval = 60
format = "%a %d.%m %R"
