[theme]
name = "gruvbox-dark"
[theme.overrides]
critical_bg = "#e06c75"
critical_fg = "#282c34"
good_bg = "#98c379"
good_fg = "#282c34"
idle_bg = "#282c34"
idle_fg = "#dcdfe4"
info_bg = "#61afef"
info_fg = "#282c34"
warning_bg = "#e5c07b"
warning_fg = "#282c34"

[icons]
name = "awesome5"

[[block]]
block = "net"
format = "{ssid} {signal_strength} {ip} {speed_up;K*b} {speed_down;K*b}"
interval = 5

[[block]]
block = "toggle"
text = "BelWü VPN UDP"
command_state = "systemctl is-active openvpn-client@via-udp | grep -v inactive"
command_on = "sudo systemctl start openvpn-client@via-udp"
command_off = "sudo systemctl stop openvpn-client@via-udp"
interval = 5

[[block]]
block = "toggle"
text = "BelWü VPN TCP"
command_state = "systemctl is-active openvpn-client@via-tcp | grep -v inactive"
command_on = "sudo systemctl start openvpn-client@via-tcp"
command_off = "sudo systemctl stop openvpn-client@via-tcp"
interval = 5
