---
name: Build and check all targets
on:
  workflow_dispatch: {}
  workflow_call:
    inputs:
      sha:
        required: true
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Remove unnecessary packages
        run: |
          echo "=== Before pruning ==="
          df -h
          sudo rm -rf /usr/share /usr/local /opt || true
          echo
          echo "=== Before building ==="
          df -h
      - name: Build system toplevel
        run: nix build github:debugloop/dotfiles/${{ inputs.sha || github.sha }}#nixosConfigurations.simmons.config.system.build.toplevel
      - name: Print leftover space
        run: |
          echo "=== After building ==="
