---
name: "Update dependencies and create a PR with necessary Build check"
on:
  push:
  schedule:
    - cron: "0 5 */1 * *"
jobs:
  update:
    runs-on: ubuntu-latest
    outputs:
      sha: ${{ steps.create-pr.pull-request-head-sha }}
      check_id: ${{ steps.create-check.outputs.check_id }}
    steps:
      - uses: actions/checkout@v4
      - uses: cachix/install-nix-action@v20
      - name: Update dependency versions in flake.lock
        run: |
          nix flake update nixpkgs
          nix flake update home-manager
          nix flake update nh
          nix flake update impermanence
          nix flake update agenix
      - name: Commit changes
        id: commit
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH=auto_update_flake_$(date -I)
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"
          git pull origin main
          git switch -c $BRANCH
          git add flake.lock
          if [[ -n "$(git status --porcelain)" ]]; then
            git commit -m "chore(automated): update flake.lock"
            git push origin $BRANCH
            gh pr create --title "Auto Update Flake Dependencies $(date -I)" --body "This is an automated PR to update Flake dependencies."
            gh pr merge --auto --delete-branch --squash "$BRANCH"
          else
            echo "No updates available today."
          fi
